{ ( 413 f :freq ) 413 = } assert

{ 1 st 2 1/12 pow = } assert
{ 5 st 2 5/12 pow = } assert
{ -3 st 2 -3/12 pow = } assert

{ 69 mtof 440 = } assert
{ 57 mtof 220 = } assert
{ 60 mtof 261.6255653005986 = } assert

{ 0 cents 1 = } assert
{ 1200 cents 2 = } assert
{ -1200 cents 0.5 = } assert
{ 100 cents 1/12 exp2 = } assert

{ c-4 48 = } assert
{ C-4 48 = } assert
{ c#4 49 = } assert
{ c-0 0 = } assert
{ b-9 119 = } assert
